package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallRedEnvelope;
import org.linlinjava.litemall.db.domain.LitemallRedEnvelopeExample;

public interface LitemallRedEnvelopeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    long countByExample(LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int insert(LitemallRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int insertSelective(LitemallRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    LitemallRedEnvelope selectOneByExample(LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    LitemallRedEnvelope selectOneByExampleSelective(@Param("example") LitemallRedEnvelopeExample example, @Param("selective") LitemallRedEnvelope.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    List<LitemallRedEnvelope> selectByExampleSelective(@Param("example") LitemallRedEnvelopeExample example, @Param("selective") LitemallRedEnvelope.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    List<LitemallRedEnvelope> selectByExample(LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    LitemallRedEnvelope selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallRedEnvelope.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    LitemallRedEnvelope selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    LitemallRedEnvelope selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallRedEnvelope record, @Param("example") LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallRedEnvelope record, @Param("example") LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallRedEnvelope record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallRedEnvelopeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_red_envelope
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}