package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStoreInventoryFlow;
import org.linlinjava.litemall.db.domain.LitemallStoreInventoryFlowExample;

public interface LitemallStoreInventoryFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    long countByExample(LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int insert(LitemallStoreInventoryFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int insertSelective(LitemallStoreInventoryFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    LitemallStoreInventoryFlow selectOneByExample(LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    LitemallStoreInventoryFlow selectOneByExampleSelective(@Param("example") LitemallStoreInventoryFlowExample example, @Param("selective") LitemallStoreInventoryFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    List<LitemallStoreInventoryFlow> selectByExampleSelective(@Param("example") LitemallStoreInventoryFlowExample example, @Param("selective") LitemallStoreInventoryFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    List<LitemallStoreInventoryFlow> selectByExample(LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    LitemallStoreInventoryFlow selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallStoreInventoryFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    LitemallStoreInventoryFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    LitemallStoreInventoryFlow selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallStoreInventoryFlow record, @Param("example") LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallStoreInventoryFlow record, @Param("example") LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallStoreInventoryFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallStoreInventoryFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallStoreInventoryFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory_flow
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}