package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallAccountFlow;
import org.linlinjava.litemall.db.domain.LitemallAccountFlowExample;

public interface LitemallAccountFlowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    long countByExample(LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int insert(LitemallAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int insertSelective(LitemallAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    LitemallAccountFlow selectOneByExample(LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    LitemallAccountFlow selectOneByExampleSelective(@Param("example") LitemallAccountFlowExample example, @Param("selective") LitemallAccountFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    List<LitemallAccountFlow> selectByExampleSelective(@Param("example") LitemallAccountFlowExample example, @Param("selective") LitemallAccountFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    List<LitemallAccountFlow> selectByExample(LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    LitemallAccountFlow selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallAccountFlow.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    LitemallAccountFlow selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    LitemallAccountFlow selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallAccountFlow record, @Param("example") LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallAccountFlow record, @Param("example") LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallAccountFlow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallAccountFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_account_flow
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}