package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallStoreInventory;
import org.linlinjava.litemall.db.domain.LitemallStoreInventoryExample;

public interface LitemallStoreInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    long countByExample(LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int insert(LitemallStoreInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int insertSelective(LitemallStoreInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    LitemallStoreInventory selectOneByExample(LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    LitemallStoreInventory selectOneByExampleSelective(@Param("example") LitemallStoreInventoryExample example, @Param("selective") LitemallStoreInventory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    List<LitemallStoreInventory> selectByExampleSelective(@Param("example") LitemallStoreInventoryExample example, @Param("selective") LitemallStoreInventory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    List<LitemallStoreInventory> selectByExample(LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    LitemallStoreInventory selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") LitemallStoreInventory.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    LitemallStoreInventory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    LitemallStoreInventory selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallStoreInventory record, @Param("example") LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallStoreInventory record, @Param("example") LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallStoreInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallStoreInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallStoreInventoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_store_inventory
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}